### ISSUE TITLE
error using  laravel-webdav(NextCloud) with spatie/backup

### ISSUE THREAD

**Issue by aguilerajl** [pascalbaljetmedia/laravel-webdav#10]
Hello,
I'm using  spatie/laravel-backup to do backups to a Nextcloud drive (webdav)

'backups' => [
'driver' => 'webdav',
'baseUri' => 'https://nextcloud.com//remote.php/dav/files/user/',
'userName' => 'user',
'password' => '******',
'pathPrefix' => '', // optional
],

The driver works fine. I can use laravel tinker and put or get any file. 
But running "php artisan backup:run" produce an error BackupDestination.php(88):
"necessary data rewind wasn't possible"

        $handle = fopen($file, 'r+');

	// this command catch an error  //
        **$this->disk->getDriver()->writeStream(
            $destination,
            $handle,
            $this->getDiskOptions()
        );**

        if (is_resource($handle)) {
            fclose($handle);
        }

Can you help me?

Thanks in advance

**Comment by pascalbaljet** [comment]
Which version of `spatie/laravel-backup` are you running?

**Comment by aguilerajl** [comment]
Hello, in my composer.json:
"spatie/laravel-backup": "^6.13",

**Comment by aguilerajl** [comment]
In command line, the followind command works:
curl https://nextcloud.com/remote.php/dav/files/userXXX/ --user userXXX --upload-file 2021-01-07-08-05-56.zip
Enter host password for user 'userXXX': ********

**Comment by pascalbaljet** [comment]
Might this be related to #9?

**Comment by wivaku** [comment]
For me (I reported #9) backup works fine. Using v6.14 of spatie/backup.
I only backup the DB (`php artisan backup:run --only-db`)

What does your backup config look like?
Here are the main changes I made (my webdav filesystem is called `webdav`, DB is sqlite):

```
...
        'name' => env('APP_NAME', 'laravel-backup') ." ". env('APP_ENV'),
...
            'databases' => [
                // 'mysql',
                env('DB_CONNECTION'),
            ],
...
        'database_dump_compressor' => Spatie\DbDumper\Compressors\GzipCompressor::class,
...
            'disks' => [
                // 'local',
                'webdav',
            ],
...
```

**Comment by aguilerajl** [comment]
> 
> 
> For me (I reported #9) backup works fine. Using v6.14 of spatie/backup.
> I only backup the DB (`php artisan backup:run --only-db`)
> 
> What does your backup config look like?
> Here are the main changes I made (my webdav filesystem is called `webdav`, DB is sqlite):
> 
> ```
> ...
>         'name' => env('APP_NAME', 'laravel-backup') ." ". env('APP_ENV'),
> ...
>             'databases' => [
>                 // 'mysql',
>                 env('DB_CONNECTION'),
>             ],
> ...
>         'database_dump_compressor' => Spatie\DbDumper\Compressors\GzipCompressor::class,
> ...
>             'disks' => [
>                 // 'local',
>                 'webdav',
>             ],
> ...
> ```

**Comment by aguilerajl** [comment]
Hello, my backup config bellow. 
I'm including backup/clean funcionalities and backup both folders and database.

```
'backup' => [
        'name' => env('APP_NAME', 'laravel-backup'),
        'source' => [
            'files' => [
                'include' => [
                    storage_path('folderInclude'),
                ],
                'exclude' => [ ],
                'follow_links' => false,
                'ignore_unreadable_directories' => false,
            ],
            'databases' => [
                'mysql',
            ],
        ],
        'database_dump_compressor' => null,
        'destination' => [
            'filename_prefix' => '',
            'disks' => [
                env('BACKUP_DRIVE', 'backups'),
            ],
        ],
        'temporary_directory' => storage_path('app/backup-temp'),
        'schedule' => [
            'clean_time' => env('CLEAN_TIME', 'backups'),
            'backup_time' => env('BACKUP_TIME', 'backups'),
        ],
    ],
```
And in the filesystem config, if I put the first driver work, and the second doesn't work,

```
'backups' => [
            'driver' => 'local',
            'root' => storage_path('backups'),
        ],
        
  
            'backups' => [
            'driver'     => 'webdav',
            'baseUri'    => 'https://nextcloud.com/remote.php/dav/files/userXXX/',
            'userName'   => 'userXXX',
            'password'   => '*******',
            'pathPrefix' => '', // optional
        ],
```

**Comment by aguilerajl** [comment]
Hello,
Referencing #9, with a slash at the end of the baseUri, all working except backup. There the results:


![Salida1](https://user-images.githubusercontent.com/55015785/104086694-48645000-525a-11eb-93ac-4a57a1b0c188.JPG)

But, without slash at the end, nothing works. It is very rare that when doing a backup you get this output:

![SinBarra](https://user-images.githubusercontent.com/55015785/104086724-7fd2fc80-525a-11eb-8d93-ac7376d64b01.jpg)

the backup has not been copied.

**Comment by aguilerajl** [comment]
Hello, referencing  #11,  this is my new filesystem config, but i continue with the error 
```
'backups' => [
'driver' => 'webdav',
'baseUri' => 'https://nextcloud.com/',
'userName' => 'user',
'password' => '******',
'pathPrefix' => 'remote.php/dav/files/user/', 
],
```
And I updated

`"spatie/laravel-backup": "^6.14",`

**Comment by wivaku** [comment]
could you try recreating the config file?
It looks quite different than the one I see on my system and in [the documentation](https://spatie.be/docs/laravel-backup/v6/installation-and-setup).
E.g. I don't see `schedule` as an option in the config file.

**Comment by aguilerajl** [comment]
Hello,
These are two entries (schedule) that I have created to facilitate backup planning. 
I don't think they have related to the problem because backups work fine if I get a local driver.
Thanks for your help.
Good Sunday :)

**Comment by aguilerajl** [comment]
Solved.
Read the following module:	..\vendor\sabre\dav\lib\DAV\Client.php
	
And then, put the authentication/encoding you need
In my case:

```
'backups' => [
	'driver'     	=> 'webdav',
	'baseUri' 		=> 'https://nextcloud.com/',
	'userName'   	=> 'userXXX',
	'password'   	=> '*******',
	'pathPrefix' 	=> 'remote.php/dav/files/userXXX/', 
	'authType'   	=>  1, //Basic authentication
]
```
