### ISSUE TITLE
How to interact with caldav / cardav ?

### ISSUE THREAD

**Issue by co5git** [pascalbaljetmedia/laravel-webdav#12]
Hi !

I found your project while looking for ways to build a basic caldav / carddav client using laravel.
It is a simple project to familiarize myself with laravel. In short I would like display and manage contacts and calendar events or tasks.

I have been reading a bit about sabredav, wich seems to be the right library for the it.
To my surprise I didn't find a lot of infos about how to integrate sabredav into laravel framework.

Am I right to understand that it is what laravel-webdav is doing ?

The README description focuses on filesystem, can it be adapted to interact with caldav calendars / carddav addessbook ?
Could you maybe point me in the right direction on how to do that ?

Thanks a lot !

**Comment by pascalbaljet** [comment]
The underlying package uses the sabre.io packages. I'd recommend using those packages: https://github.com/sabre-io
