### ISSUE TITLE
Compatability Laravel 6.0

### ISSUE THREAD

**Issue by alexander-rieder** [pascalbaljetmedia/laravel-webdav#4]
Hey :)
will this package be updated to be compatible to upcoming Laravel 6.0?

Greetings,
Alex

**Comment by pascalbaljet** [comment]
Yes! I will tag a new release next week ;-)

**Comment by pascalbaljet** [comment]
Fixed in v1.6.0: https://github.com/pascalbaljetmedia/laravel-webdav/releases/tag/1.6.0
